### ISSUE TITLE
widget.Text param:validator using a function not takes the current value.

### ISSUE THREAD

**Issue by franklintimoteo** [peterbrittain/asciimatics#152] opened 2018-05-03 23:47 UTC
https://github.com/peterbrittain/asciimatics/blob/4d8279a4d1fc095c6ce26b0c4fb5702992f2e268/asciimatics/widgets.py#L1592

```python
#works
#self.text_count = Text(label="Count", validator=lambda x: True if x.isdigit() else False)

#not works
self.text_count = Text(label="Count", validator=self._valid_char)
#_valid_char, not takes any value
@staticmethod
def _valid_char(self, char):
     ...
```
whitout staticmethod raise an exception:
`TypeError: first argument must be string or compiled pattern`

Is it a error?

Using:
C9 IDE
Python 3.5.3 (default, Apr 22 2017, 00:00:00) 
[GCC 4.8.4]

**Comment by peterbrittain** [comment] 2018-05-04 08:35
I don't think that your sample code above matches what you're actually running...  You've delcared a staticmethod with a `self` parameter, which will raise a very different error when you run the code.

The forms.py sample already contains a static method validator, so I know that this works for some cases....  Can you please try to reproduce the problem with that sample?  If you can, please tell me the steps required to hit this issue.

**Comment by peterbrittain** [comment] 2018-05-04 11:01
Hold on a sec...  Do you mean that you can't use instance methods as your validator function?

**Comment by peterbrittain** [comment] 2018-05-04 22:00
Ok, I see the issue for the instance method and have fixed it with https://github.com/peterbrittain/asciimatics/commit/cfbe2aa43ccf341041f4447d42e15d489f30c2fd.

I don't get any error running your lambda function gist, though.  Can you give me your full stack for that error too?

**Comment by franklintimoteo** [comment] 2018-05-04 22:57
Ohh, lambda functions works! I only demonstrate that using lambda takes 1 args, but with normal functions not takes args.

**Comment by peterbrittain** [comment] 2018-05-04 23:27
OK!  In that case, this is fixed.  I'll close the issue.

Note that your sample code for the instance method will hit a recursion error with this fix because you are setting a new value inside the validator.  You don't need to do this as the value is already set by the widget.  The validator should simply check whether the current value is syntactically correct and return True/False accordingly.

**Closed by peterbrittain** 2018-05-04 23:27 UTC
Labels: bug
