### ISSUE TITLE
i can't scroll down in ListBox 

### ISSUE THREAD

**Issue by DarkCode01** [peterbrittain/asciimatics#180] opened 2018-10-15 19:29 UTC
**Describe the bug**
When insert to options values in widget ListBox, this dows not allow me to move in the list values.

**System details (please complete the following information):**
 - OS and version: [e.g. Windows 10
 - Asciimatics ersion [e.g. 1.9.0]

**Comment by peterbrittain** [comment] 2018-10-15 22:11
I've just tried it out on the contact list sample and it's working fine for me.  Can you please be a little more specific in how you reproduce the problem?

**Comment by peterbrittain** [comment] 2018-10-18 21:35
I've now even fixed up the contact_list demo so that it shows the right scrollbar.  All looks fine to me.  I'm assuming that it's also working for you since you haven't replied, so am closing.

**Closed by peterbrittain** 2018-10-18 21:35 UTC
