### ISSUE TITLE
Non Full Screen Options

### ISSUE THREAD

**Issue by jtpereyda** [peterbrittain/asciimatics#274] opened 2020-10-14 19:06 UTC
**Is your feature request related to a problem? Please describe.**
I would like to rewrite a few lines of console output without pivoting to a full screen application. This has some UX advantages in certain situations. Honggfuzz is one application with this style of output.

**Describe the solution you'd like**
A way to rewrite multiple lines -- sort of like a progress bar, but a little more generic, and not full screen. See https://stackoverflow.com/q/6840420/461834 for an example.

**Describe alternatives you've considered**
I've looked at lots of Python libraries out there but haven't quite found it yet. The most common category is full screen app, or progress bars.

**Additional context**
Asciimatics is probably the preeminent Python library for curses style console output. It seems appropriate to support this use case as well.

May be related to #46

**Comment by jtpereyda** [comment] 2020-10-14 19:19
More details on the use case:
1. I want to preserve log messages before using my fancy asciimatics TUI, stop the TUI, then send log messages after.
2. I want to allow scrollback while updating the output.

Example (based on the asciimatics hello world):
```python
from random import randint
from asciimatics.screen import Screen

print("[*] Important log message 1")

def demo(screen):
    while True:
        screen.print_at('Hello world!',
                        randint(0, screen.width), randint(0, screen.height),
                        colour=randint(0, screen.colours - 1),
                        bg=randint(0, screen.colours - 1))
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            return
        screen.refresh()

Screen.wrapper(demo)

print("[*] Important log message 2")
```

Both log messages get overwritten or are otherwise not seen when I run the program.

**Comment by peterbrittain** [comment] 2020-10-14 21:36
Not sure whatthat ,astdemois meant to show me...  When i run it on Linux, it hides the first printed message, then (after I press Q), it reinstates the screen, prints the second message and quits.

I'm guessing you want the fancy TUI to appear over the top of the existing terminal output.  If so, you really have 2 options:

1) You run the program that uses print as a separate process and embed that output in a widget.  Look at terminal.py for a way to do that on unix systems.  There are similar APIs in Windows (e.g. conpty), but I haven't created a demo for that.
2) Write a program that takes control of the terminal and uses control sequences to move the cursor  and draw the TUI, then move the cursor back to the last output and set a scroll region to prevent it from moving the TUI.  This requires #46.

**Comment by jtpereyda** [comment] 2020-10-14 22:14
> When I run it on Linux, it hides the first printed message, then (after I press Q), it reinstates the screen, prints the second message and quits.

Oh... I was hitting Ctrl+C. I guess it'd be possible to catch the interrupt and quit properly, thus reinstating the screen.

> Write a program that takes control of the terminal and uses control sequences to move the cursor and draw the TUI, then move the cursor back to the last output and set a scroll region to prevent it from moving the TUI. This requires #46.

I just figured out how to do this manually. Linking my answer in case it helps future readers https://stackoverflow.com/a/64362146/461834

But using a full asciimatics widget in this context would be really cool -- guess #46 might help with that.

**Comment by peterbrittain** [comment] 2020-10-15 08:14
Those control sequences aren't the full story, but they will get something up and running quickly.

Other things to consider are:

- Each terminal has it's own unique set of control codes. ANSI codes are safe on most terminals now, but you should really use the terminfo database to find them.
- You may hit problems in Windows - even with colorama.
- To handle a truly separate widget on the Screen simply moving up and down won't work.  You'll need to use sequences like DECSTBM, DECSC and DECRC. 

https://www.vt100.net/docs/vt510-rm/DECSTBM.html
https://www.vt100.net/docs/vt510-rm/DECSC.html
https://www.vt100.net/docs/vt510-rm/DECRC.html

These are features I'm considering for #46, but obviously not supported today.

**Comment by peterbrittain** [comment] 2020-10-15 08:16
Given all the above I think this is a duplicate of 46, so am closing this issue.  Please shout if I've missed something...

**Closed by peterbrittain** 2020-10-15 08:16 UTC
