### ISSUE TITLE
Any chance we can get is simple Hello world example?

### ISSUE THREAD

**Issue by robuis** [peterbrittain/asciimatics#135] opened 2018-02-16 20:59 UTC
I am looking to draw a screen print hello world, refresh, and wait for user input.
Tried 
def demo(screen):
    screen.print_at('Hello world!', 0, 0)
    screen.refresh()
    sleep(10)
Screen.wrapper(demo)
But sleep is not defined.

**Comment by robuis** [comment] 2018-02-16 21:30
I believe I have found that code.

def demo(screen):
    while True:
        screen.print_at('Hello world!',0, 0)
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            return
        screen.refresh()
Screen.wrapper(demo)

Now, what if I have a list or a dict of data I need to send to the screen? 

I was thinking 

def demo(screen):
    while True:
        X = 0
        y = 0
        for i in somelist/somedict:
            screen.print_at(i, x, y)
            y + 1
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            return
        screen.refresh()

Screen.wrapper(demo)

**Comment by robuis** [comment] 2018-02-16 21:44
I should probably say. 

I have a list/dict, and I want to print each item in the list on the screen, or each ['key'],in the dict on the screen.

It's an event log with  Type: TimeStamp: Message: keys.

**Comment by peterbrittain** [comment] 2018-02-17 12:41
It's not clear what the problem is in your second piece of code.  There are a couple of bugs:

1.  You aren't actually defining `x` before you use it, because of a case mismatch.
2.  You aren't saving the updated value of `y`.

The rest looks fine assuming your list/dict contains strings.

**Comment by peterbrittain** [comment] 2018-02-21 22:12
I'm assuming that's fixed it for you, so am closing.  Feel free to reply if it's not resolved.

**Closed by peterbrittain** 2018-02-21 22:12 UTC
Labels: question
